{% set version = "20200125" %}
{% set name = "m4rie" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/malb/{{ name }}/archive/refs/tags/release-{{ version }}.tar.gz
  sha256: a0c3f46c399ed2e4af5aaad9de9db0962d15d5ccb9bd0e313df6b2c16bf8e0b1

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("m4rie") }}


requirements:
  build:
    - libtool
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
  host:
    - libpng
    - zlib
    - m4ri

test:
  commands:
    - test -f ${PREFIX}/include/m4rie/m4rie.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: https://github.com/malb/m4rie
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: M4RIE is a library for fast arithmetic with dense matrices over GF(2^e) for 2 ≤ e ≤ 16.
  dev_url: https://github.com/malb/m4rie

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
