{% set version = "20250128" %}
{% set name = "m4rie" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/malb/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 96f1adafd50e6a0b51dc3aa1cb56cb6c1361ae7c10d97dc35c3fa70822a55bd7

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("m4rie") }}


requirements:
  build:
    - libtool
    - make
    - automake   # [unix]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - libpng
    - zlib
    - m4ri

test:
  commands:
    - test -f ${PREFIX}/include/m4rie/m4rie.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: https://github.com/malb/m4rie
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: M4RIE is a library for fast arithmetic with dense matrices over GF(2^e) for 2 ≤ e ≤ 16.
  dev_url: https://github.com/malb/m4rie

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
