{% set version = "20250102" %}
{% set name = "m4rie" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/malb/{{ name }}/archive/refs/tags/release-{{ version }}.tar.gz
  sha256: 49cb30c063800a5b5c575be12570981e06c9d336a43bb44f0f66420e1d8e2b39

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("m4rie") }}


requirements:
  build:
    - libtool
    - make
    - automake   # [unix]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - libpng
    - zlib
    - m4ri

test:
  commands:
    - test -f ${PREFIX}/include/m4rie/m4rie.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: https://github.com/malb/m4rie
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: M4RIE is a library for fast arithmetic with dense matrices over GF(2^e) for 2 ≤ e ≤ 16.
  dev_url: https://github.com/malb/m4rie

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
