travis:
  secure:
    BINSTAR_TOKEN: Oyt0fgqHG0qx87l4Fc6sJLyVCViL0RZdcsYgn2wceKhmxzfkoqMFbteI6SW16vxF8NoulOo8abddPRrwFdmgRoyai6PMxf6qARMIRbSwHePc4u+0kK3HhuZNO8uKAYO6kiWhbbthYa6LZWd6V2PP5Z07jsUIbaxBGh8EyrNuNwihZTyfdSJIyYmFka4pBxS8X5CNPvfUlDIPN3gRs3solqBlH6QZcgeXiQO+MKtFOxbzX++lmSv9okLsrk0g1thxvgs8fMWOkNg19dkDpOJnQLIX4WTkHlbKTW423j32gnm03oeASqiaFhYplQFx2F9kvDcmjjKLY7vgZ0y47PcqEWsFnTXD5QGBJ5UDc9flQclFA3aDThIib9x4C62obdWIBsxW46OaAnRfF4KBFBBi0TxoxpfR/TyHlBqFEYdIApRERD7ZidpuA9x+0ibq3R2p7nmyR/Ol4rzaRCCA5jK2yvMPLpQP57tAvrsHmiNzxibCrorTIaoBtlBmUs7DhUTGpgFQlsgfSbAKXEt2yMLnRH1IBj1sZrucwY/kWT4EbwefjSyCfEhgrqvF6RV5mxdNPvs1cb3ntAVbnFItMHJ35OIgqYa/PE6DxVkilhdsjKBBeJXrXR6zi4Pu8iWypZKbMLQ377szdaMr/sB3VJrvKeLfe0Ppx5iZ67tI5QeLtCU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
