appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: mlLBfO1w5UD43vkAlg3M330MaMIDgHzOPLd8Ve9ZkbzhBvP4sGnaSoZCNAAWI8R+YzU8XIPrsLXDvQaKexxIv34agJEXHicOou6ASmSiWBEvcM3+PBhoB4QbhLHfExmt9TBh0G/de6WE3tO/QlI/DThRhIKLklzKqpxag9DZvScYpNF3KnPgtPdH7eqX3JXM723SXbpiGLielP8himCvbcYK2FiADfnUWo931YfqMZqk5aVvu7PmS74z2tWxxfhIxF3vwqgdVcJCfSca8YPq6wY8sv8SLsd+cmZnV3GxjmsfxTYalkgOuI/HUQaEY94qIwyiBiyMbw+D6KdQtfZ0TmQi5ePGkDv4OuCw6zrFzqvf1PyRXxy5KSAm69hCq3BPaJq4dsZT0LTQBvbwGCnafkWQlYJOWQY939NRG5Ibu9X6/DCzWiXVM5XHwjgta2JBSst317fW9b8IC/IOTNo9eh5xaYd4eAL+/wevkYQDeVglcfHbbQc5Fo+Pc5aSyQ6BOTxDbfy2OTKiUIy4BPLoYAYGA+gijX1eWzuCYQ0tFgXGA0Tn3iAfY+f7YdToe8lK7hHMtbdy6j3OmBCSWAtpcDhax6przYLKar37q3cFh6a5BKl/XYy76OzcdxpyMzF/LOqCQrfwacprd9sJi05DKYR/DY9sq5+EO8rxwIrg9wc=}
conda_forge_output_validation: true
