@echo off

:: PLEASE NOTE: This script has been automatically generated by conda-smithy. Any changes here
:: will be lost next time ``conda smithy rerender`` is run. If you would like to make permanent
:: changes to this script, consider a proposal to conda-smithy so that other feedstocks can also
:: benefit from the improvement.

set "FEEDSTOCK_ROOT=%~dp0.."

if "%MINIFORGE_HOME%"=="" set "MINIFORGE_HOME=%USERPROFILE%\miniforge3"

IF EXIST "%MINIFORGE_HOME%\Scripts\activate.bat" (
    echo "Miniforge already installed, activating..."
) ELSE (
    echo "Downloading miniforge..."
    powershell -Command "(New-Object Net.WebClient).DownloadFile('https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-x86_64.exe', '%TEMP%\miniforge.exe')"
    if %ERRORLEVEL% neq 0 exit 1
    echo "Installing miniforge..."
    %TEMP%\miniforge.exe /S /D=%MINIFORGE_HOME%
    if %ERRORLEVEL% neq 0 exit 1
)

call "%MINIFORGE_HOME%\Scripts\activate.bat"
if %ERRORLEVEL% neq 0 exit 1

call conda install --yes --quiet --channel conda-forge ^
    pip python=3.12 conda-build conda-forge-ci-setup=4 "conda-build>=24.1"
if %ERRORLEVEL% neq 0 exit 1

set "CONDA_LIBMAMBA_SOLVER_NO_CHANNELS_FROM_INSTALLED=1"

call setup_conda_rc "%FEEDSTOCK_ROOT%" "%FEEDSTOCK_ROOT%\recipe" "%FEEDSTOCK_ROOT%\.ci_support\%CONFIG%.yaml"
if %ERRORLEVEL% neq 0 exit 1

call run_conda_forge_build_setup_win
if %ERRORLEVEL% neq 0 exit 1

call make_build_number "%FEEDSTOCK_ROOT%" "%FEEDSTOCK_ROOT%\recipe" "%FEEDSTOCK_ROOT%\.ci_support\%CONFIG%.yaml"
if %ERRORLEVEL% neq 0 exit 1

if exist "%FEEDSTOCK_ROOT%\LICENSE.txt" (
    copy "%FEEDSTOCK_ROOT%\LICENSE.txt" "%FEEDSTOCK_ROOT%\recipe\recipe-scripts-license.txt"
)

if "%BUILD_WITH_CONDA_DEBUG%"=="1" (
    if not "%BUILD_OUTPUT_ID%"=="" (
        set "EXTRA_CB_OPTIONS=%EXTRA_CB_OPTIONS% --output-id %BUILD_OUTPUT_ID%"
    )
    call conda debug "%FEEDSTOCK_ROOT%\recipe" ^
        -m "%FEEDSTOCK_ROOT%\.ci_support\%CONFIG%.yaml" ^
        --clobber-file "%FEEDSTOCK_ROOT%\.ci_support\clobber_%CONFIG%.yaml"
    if %ERRORLEVEL% neq 0 exit 1
) ELSE (
    call conda-build "%FEEDSTOCK_ROOT%\recipe" ^
        -m "%FEEDSTOCK_ROOT%\.ci_support\%CONFIG%.yaml" ^
        --suppress-variables %EXTRA_CB_OPTIONS% ^
        --clobber-file "%FEEDSTOCK_ROOT%\.ci_support\clobber_%CONFIG%.yaml" ^
        --extra-meta flow_run_id="%flow_run_id%" remote_url="%remote_url%" sha="%sha%"
    if %ERRORLEVEL% neq 0 exit 1

    call inspect_artifacts --recipe-dir "%FEEDSTOCK_ROOT%\recipe" -m "%FEEDSTOCK_ROOT%\.ci_support\%CONFIG%.yaml" || echo "inspect_artifacts needs conda-forge-ci-setup >=4.9.4"

    call validate_recipe_outputs "%FEEDSTOCK_NAME%"
    if %ERRORLEVEL% neq 0 exit 1

    if "%UPLOAD_PACKAGES%" NEQ "False" (
        if "%IS_PR_BUILD%" == "False" (
            call upload_package --validate --feedstock-name="%FEEDSTOCK_NAME%" ^
                "%FEEDSTOCK_ROOT%" "%FEEDSTOCK_ROOT%\recipe" "%FEEDSTOCK_ROOT%\.ci_support\%CONFIG%.yaml"
            if %ERRORLEVEL% neq 0 exit 1
        )
    )
)
